### ISSUE TITLE
Please can we make the homepage main logo even bigger 

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/butlrhr#2]
The existing site looks like this - http://www.butlerhr.com.au/jobs/

Not as big as this but would like to increase it.

**Comment by markendley** [comment]
because he wants the "HR" to stand out more right

**Comment by LaraStudioFriday** [comment]
I emailed you the updated logos - it has Find Success under Butler HR

**Comment by markendley** [comment]
done
