### ISSUE TITLE
Can we make the menu and drop down items also bigger

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/butlrhr#3]
Not as big as existing site - http://www.butlerhr.com.au/jobs/

<img width="914" alt="Screen Shot 2019-10-15 at 11 42 16 am" src="https://user-images.githubusercontent.com/55725505/66791686-f3476a80-ef40-11e9-98b4-840be9511e0f.png">

But they need to increase in size

**Comment by markendley** [comment]
done

**Comment by LaraStudioFriday** [comment]
Can we please go bigger - the drop down menus still look fairly small.

**Comment by markendley** [comment]
better?
