### ISSUE TITLE
Who is Butler HR

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/butlrhr#4]
I have added a new section at the top of the About us page. Can the menu item for 'Who is Butler HR) link to this section and not the one below. 

Should link to - 

<img width="1211" alt="Screen Shot 2019-10-15 at 2 04 20 pm" src="https://user-images.githubusercontent.com/55725505/66797935-17fb0c80-ef58-11e9-94ea-787f725be3bb.png">

Not to this section:

<img width="1221" alt="Screen Shot 2019-10-15 at 2 07 12 pm" src="https://user-images.githubusercontent.com/55725505/66797920-0f0a3b00-ef58-11e9-98ef-0dbc57789709.png">

**Comment by markendley** [comment]
done
