### ISSUE TITLE
Telephone number in header

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/butlrhr#5]
Client would like this position on the right hand side instead of left. 

Can we right align this under contact?

I know this might be a squeeze, so do we just make the blue header in a larger height?

**Comment by markendley** [comment]
easy done

**Comment by LaraStudioFriday** [comment]
Can you please move this down. 

So you see the distance from Contact to Call us on - can you please position (Call us on and the number) so it sits equal distance from the top and bottom of the blue header bar. 
<img width="737" alt="Screen Shot 2019-10-21 at 10 17 46 am" src="https://user-images.githubusercontent.com/55725505/67168118-89b9d700-f3ec-11e9-86a5-34a30ac1abab.png">


<img width="253" alt="Screen Shot 2019-10-21 at 10 18 28 am" src="https://user-images.githubusercontent.com/55725505/67168113-760e7080-f3ec-11e9-8ebf-108c82753009.png">

**Comment by markendley** [comment]
done
