### ISSUE TITLE
Logos on a phone

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/butlrhr#7]
![72756393_1426522357523293_1312357120200409088_n](https://user-images.githubusercontent.com/55725505/67248456-46c13780-f4b0-11e9-897e-4e39b274afd1.jpg)
![73482563_681595745661276_1817972150733111296_n](https://user-images.githubusercontent.com/55725505/67248457-46c13780-f4b0-11e9-9f5d-9cd7713d96e7.jpg)

The spacing between the logos is pretty big - could we put 2 logos on 1 line and reduce the spacing between the lines a little more?

**Comment by markendley** [comment]
done
