### ISSUE TITLE
Big white space

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/butlrhr#8]
<img width="1247" alt="Screen Shot 2019-10-24 at 2 28 31 pm" src="https://user-images.githubusercontent.com/55725505/67450909-9e0b0780-f66a-11e9-8e11-acdf6ac5c720.png">

on this page ; http://marke2.sg-host.com/butler/job/project-manager-logistics-analyst/

**Comment by markendley** [comment]
I don't see it, in that white space I see youtube video

did you fix this already

or maybe it just took a little while for the youtube to load?
